spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  properties:
    hibernate:
      format_sql: true
  hibernate:
    ddl-auto: create
  h2:
    console:
      enabled: true
  messages:
    always-use-message-format: false
    fallback-to-system-locale: true
    basename: messages
  jackson:
    default-property-inclusion: non_null


hibernate:
  dialect: org.hibernate.dialect.H2Dialect

logging:
  level:
    org.springframework: ERROR
    com.university.enrollment: INFO

university:
  userTypes:
    - ADMIN
    - REGULAR